### ISSUE TITLE
Requires content updates from the Legacey Wiki - Source Code info Missing

### ISSUE THREAD

**Issue by kerberosmansour** [OWASP/www-project-cloud-security#1]
@hblankenship can you please update this project page with links to the correct code repo at least?
Wiki page
https://wiki.owasp.org/index.php/OWASP_Cloud_Security_Project
Source code
https://github.com/owasp-cloud-security/owasp-cloud-security

**Comment by hblankenship** [comment]
No pull request?  :)  I added the repo and I will contact the project leader to see if he is still involved.
